felis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from rest_framework import routers
from django.contrib.auth import views as auth_views
from felis.views import *


urlpatterns = [
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/img/felis.ico', permanent=True)),
    url(r'^$', HomePageView.as_view(), name='home'),

    # Interfaces
    url(r'^interface/(?P<pk>\d+)', InterfaceDetailView.as_view(), name='interface'),
    url(r'^interface/', InterfaceListView.as_view(), name='interfaces'),

    # IP addresses
    url(r'^ipaddress/(?P<pk>\d+)', IPAddressDetailView.as_view(), name='ipaddress'),
    url(r'^ipaddress/', IPAddressListView.as_view(), name='ipaddresses'),
    # Worlds
    url(r'^world/(?P<pk>\d+)', WorldDetailView.as_view(), name='world'),
    url(r'^world/', WorldListView.as_view(), name='worlds'),

    # Skels
    url(r'^skel/(?P<pk>\d+)', SkelDetailView.as_view(), name='skel'),
    url(r'^skel/', SkelListView.as_view(), name='skels'),

    # Filesystems
    url(r'^filesystem/(?P<pk>\d+)', FilesystemDetailView.as_view(), name='filesystem'),
    url(r'^filesystem/', FilesystemListView.as_view(), name='filesystems'),

    # Jails
    url(r'^jail/(?P<pk>\d+)', JailDetailView.as_view(), name='jail'),
    url(r'^jail/', JailListView.as_view(), name='jails'),

    # Transactions
    url(r'^transactions', TransactionListView.as_view(), name='transactions'),

    # Charts
    url(r'^chart/(?P<pk>\d+)/rctl_iochart', RctlIOChartView.as_view(), name='rctl_io_chart'),
    url(r'^chart/(?P<pk>\d+)/rctl_(?P<attribute>[a-z_-]+)', RctlChartView.as_view(), name='rctl_chart'),
    url(r'^chart/(?P<pk>\d+)/fs_diagram', FSDiagramView.as_view(), name='fs_diagram_chart'),
    url(r'^chart/(?P<pk>\d+)/fs', FSChartView.as_view(), name='fs_chart'),
    url(r'^chart/(?P<pk>\d+)/(?P<attribute>[a-z_-]+)', ChartView.as_view(), name='chart'),

    # API
    # Wire up our API using automatic URL routing.
    # Additionally, we include login URLs for the browsable API.
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    # Logs
    url(r'^errorlog/', ErrorLogView.as_view(), name='errorlog'),

]

felis/models/transaction.py
# -*- coding: utf-8 -*-

import logging
import django.db.models as models
from django.utils import timezone
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.contrib.postgres.fields import JSONField
from django.contrib.contenttypes.models import ContentType
from django.core.cache import caches
from django_q.models import Task
from polymorphic.models import PolymorphicModel
from felis.errors import *

__all__ = ['Transaction', 'Model']

logger = logging.getLogger('felis.models')

class Transaction(models.Model):
    """
    Represents a change or set of changes in a :model:`felis.Model`'s instance that may require executing some tasks.
    Also :model:`felis.Transaction`'s instances may be used as a historical marks for some :model:`felis.Model`'s fields.
    """

    class Meta:
        verbose_name = 'Transaction'
        ordering = ["-pk"]

    cache = caches['transaction']

    CREATE = 0
    UPDATE = 1
    DELETE = 2

    instance = models.ForeignKey(
        'Model', related_name='transactions', on_delete=models.SET_NULL,
        null=True, db_index=True, blank=True, editable=False)
    content_type = models.ForeignKey(ContentType, null=True, db_index=True, blank=True)

    change_type = models.PositiveSmallIntegerField(
        choices=((CREATE, 'CREATE'), (UPDATE, 'UPDATE'), (DELETE, 'DELETE')),
        db_index=True
    )

    created = models.DateTimeField(auto_now_add=True)
    started = models.DateTimeField(null=True, default=None, db_index=True, blank=True)
    committed = models.DateTimeField(null=True, default=None, db_index=True, blank=True)
    rolledback = models.DateTimeField(null=True, default=None, db_index=True, blank=True)
    value = JSONField(null=True, db_index=True, blank=True)
    task = models.OneToOneField(Task, related_name='transaction', null=True, db_index=True, blank=True, editable=False)
    depends = models.ManyToManyField('self', symmetrical=True, db_index=True, blank=True, editable=False)
    priority = models.PositiveSmallIntegerField(db_index=True, null=True, blank=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, db_index=True, null=True, blank=True)

    def full_clean(self, *args, **kwargs):
        # transaction cannot be committed and rolledback simultaneously
        if self.committed and self.rolledback:
            msg = _("Transaction cannot be committed and rolled back simultaneously")
            raise ValidationError({'committed': [msg, ], 'rolledback': [msg, ]})

        # validating `change_type' field
        if (self.change_type == self.CREATE)\
                and self.value is None\
                and self.instance is not None:
            pass
        elif (self.change_type == self.UPDATE) \
                and self.value is not None\
                and self.instance is not None:
            pass
        elif (self.change_type == self.DELETE)\
                and self.value is not None\
                and self.instance is None:
            pass
        else:
            raise ValidationError({'change_type': [_(
                "Didnt expected data for change of type {0}").format(self.change_type), ]})

        # setting priority
        if self.priority is None:
            self.priority = self.get_priority()

        super(Transaction, self).full_clean(*args, **kwargs)

    @property
    def previous(self):
        return self.instance.transactions.filter(committed__lt=self.created).order_by('-committed').first()

    @property
    def next(self):
        return self.instance.transactions.filter(committed__gt=self.created).order_by('committed').first()

    @property
    def cached_data(self):
        return self.cache.get(self.pk, None)

    @property
    def old_values_dict(self):
        cached_values = self.cache.get(self.pk, dict())
        if cached_values and 'old' in cached_values:
            return cached_values['old']
        d = None
        if self.new_values_dict:
            d ={**self.new_values_dict, **self.value}
        if d is None and self.instance:
            d = {**self.instance.as_dict(), **self.value}
        if d is not None:
            self.cache.set(self.pk, {**cached_values, 'old': d})
        return d

    @property
    def new_values_dict(self):
        cached_values = self.cache.get(self.pk, dict())
        if cached_values and 'new' in cached_values:
            return cached_values['new']
        d = None
        if ('cached' in self.next.cached_data) or \
                ('cached' in self.next.next.cached_data) or \
                ('cached' in self.next.next.next.cached_data):
                d = {**self.next.new_values_dict, **self.next.value}
        if d is not None:
            self.cache.set(self.pk, {**cached_values, 'new': d, 'cached': True})
        # cached values to far from this transaction
        if d is None:
            d = self.instance.as_dict()
        return d

    @property
    def field(self):
        if self.value and len(self.value.keys()) == 1:
            return list(self.value.keys())[0]

    @property
    def fields(self):
        if self.value:
            return list(self.value.keys())

    @property
    def task_name(self):
        if self.change_type == self.CREATE:
            return 'task_create'
        elif self.change_type == self.UPDATE:
            if self.field:
                return 'task_update_' + self.field
        elif self.change_type == self.DELETE:
            return 'task_delete'

    @property
    def old_instance(self):
        if self.value is None:
            return None

        instance = self.content_type.model_class()()
        for field in instance._meta.fields:
            try:
                if isinstance(field, models.ForeignKey):
                    setattr(instance, field.name + '_id', self.old_values_dict[field.name])
                else:
                    setattr(instance, field.name, self.old_values_dict[field.name])
            except KeyError:
                setattr(instance, field.name, None)
        return instance

    def get_priority(self):
        if self.instance is None and self.change_type != self.DELETE:
            # empty priority, will never execute
            return 0
        if self.change_type == self.CREATE:
            if hasattr(self.instance, 'task_create_priority'):
                return self.instance.task_create_priority
            else:
                # default for CREATE task
                return 100
        elif self.change_type == self.UPDATE:
            if self.field:
                if hasattr(self.instance, 'task_update_'+self.field):
                    return getattr(self.instance, 'task_update_'+self.field+'_priority')
            # default for UPDATE task
            return 50
        elif self.change_type == self.DELETE:
            if hasattr(self.instance, 'task_delete_priority'):
                return self.instance.task_delete_priority
            else:
                # default for DELETE task
                return 90


    def render_command(self, command):
        """Replaces curly-braced words in `command' with values of corresponding models fields"""
        import string

        if command is None or self.instance is None:
            return
        return command.format(**{
            i[1].split('.')[0]: getattr(self.instance, i[1].split('.')[0])
            for i
            in string.Formatter().parse(command.strip())
            if i is not None and i[1] is not None
            })

    def exec(self, command):
        import subprocess
        import shlex
        import os
        if command:
            rendered_command = self.render_command(command)
            logger.info('Running command {0}'.format(rendered_command))
            with subprocess.Popen(
                            ['sudo'] + shlex.split(rendered_command),
                    stdin=subprocess.PIPE,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    env=os.environ.copy()
            ) as p:
                stdout, stderr = p.communicate()
                if p.returncode != 0:
                    raise TaskFailed("Execution of command `{0}' failed with errorcode {1}: {2}".format(
                        rendered_command, p.returncode, stderr))
                return stdout, stderr

    def commit(self):
        logger.info("Executing task for \n"
                    "{transaction}:\n"
                    "instance\t=\t{instance}\n"
                    "content_type\t=\t{content_type}\n"
                    "change_type\t=\t{change_type}\n"
                    "created\t=\t{created}\n"
                    "started\t=\t{started}\n"
                    "committed\t=\t{committed}\n"
                    "rolledback\t=\t{rolledback}\n"
                    "value\t=\t{value}\n"
                    "field\t=\t{field}\n"
                    "task\t=\t{task}\n"
                    "depends\t=\t{depends}\n"
                    "priority\t=\t{priority}\n"
                    "author\t=\t{author}\n"
                    "old_field_value\t=\t{old_field_value}\n"
                    "new_field_value\t=\t{new_field_value}".format(
            transaction=self,
            instance=self.instance,
            content_type=self.content_type,
            change_type=self.change_type,
            created=self.created,
            started=self.started,
            committed=self.committed,
            rolledback=self.rolledback,
            value=self.value,
            field=self.field,
            task=self.task,
            depends=self.depends.all(),
            priority=self.priority,
            author=self.author,
            old_field_value=self.old_values_dict[self.field],
            new_field_value=self.new_values_dict[self.field])
        )

        instance = self.instance
        if self.change_type == Transaction.DELETE:

felis/views/filesystem.py
# -*- coding: utf-8 -*-

from django.views.generic import DetailView, ListView
from felis.models import Filesystem

__all__ = ['FilesystemListView', 'FilesystemDetailView']

class FilesystemListView(ListView):
    template_name = 'listviews/filesystems.html'
    model = Filesystem


class FilesystemDetailView(DetailView):
    model = Filesystem
    template_name = 'detailed/filesystem.html'

felis/views/jail.py
# -*- coding: utf-8 -*-

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from felis.models import Jail
from felis.models.rctl import rctls

__all__ = ['JailDetailView', 'JailListView']

class JailDetailView(DetailView):
    model = Jail
    template_name = 'detailed/jail.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        status = request.GET.get('status', None)
        console = request.GET.get('console', None)

        if status in ['r', 'start', 'on', '1']:
            self.object.status = Jail.STARTING
        elif status in ['s', 'stop', 'off', '0']:
            self.object.status = Jail.STOPPING
        if console in ['yes', 'on', 'true', '1']:
            self.object.console = True
        elif console in ['no', 'off', 'false', '0']:
            self.object.console = False
        if status or console:
            self.object.save()
            return HttpResponseRedirect(reverse_lazy('jail', kwargs={'pk': self.object.pk}))

        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(JailDetailView, self).get_context_data(**kwargs)
        context['ssh'] = 'ssh felis@'+self.request.get_host()+' -p'+str(50000+self.object.id)
        context['charts'] = [i[0] for i in rctls]
        return context


class JailListView(ListView):
    template_name = 'listviews/jails.html'
    model = Jail

felis/views/transactions.py
# -*- coding: utf-8 -*-

from django.db.models import Q
from django.views.generic import ListView
from felis.models import Transaction
from .pagination import PaginationMixin

__all__ = ['TransactionListView']

class TransactionListView(ListView, PaginationMixin):
    model = Transaction
    template_name = 'listviews/transactions.html'

    def get_queryset(self):
        show_system = self.request.GET.get('show_system', None)
        if show_system:
            return self.model.objects.all()
        else:
            return self.model.objects.filter(~Q(author=None))

    def get_context_data(self, **kwargs):
        context_data = super(TransactionListView, self).get_context_data(**kwargs)
        context_data['show_system'] = self.request.GET.get('show_system', None)
        return self.add_paginator(context_data)

templates/listviews/filesystems.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}Felis{% endblock %}

{% block content %}
    <table class="table">
            <tr>
                <th>#</th>
                <th>name</th>
                <th>description</th>
                <th>zfs path</th>
                <th>path</th>
                <th>snapshots</th>
            </tr>
        {% for line in object_list %}
            <tr class="clickable-row" data-href="{{ line.get_absolute_url }}">
                <td>{{ line.id }}</td>
                <td>{{ line.name }}</td>
                <td>{{ line.description }}</td>
                <td>{{ line.zpath }}</td>
                <td>{{ line.path }}</td>
                <td>
                    {% if line.snapshots.all %}
                        {% for s in line.snapshots.all %}
                            {{ s.name }}&nbsp;
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <hr>

{% endblock %}

{% block context_menu %}
    <a href="{% url 'admin:felis_filesystem_add' %}">Add</a>
{% endblock %}

templates/listviews/interfaces.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}Felis{% endblock %}

{% block content %}
    <table class="table">
            <tr>
                <th>#</th>
                <th>name</th>
                <th>description</th>
                <th>zfs path</th>
                <th>path</th>
                <th>snapshots</th>
            </tr>
        {% for line in object_list %}
            <tr class="clickable-row" data-href="{{ line.get_absolute_url }}">
                <td>{{ line.id }}</td>
                <td>{{ line.name }}</td>
                <td>{{ line.description }}</td>
                <td>{{ line.zpath }}</td>
                <td>{{ line.path }}</td>
                <td>
                    {% if line.snapshots.all %}
                        {% for s in line.snapshots.all %}
                            {{ s.name }}&nbsp;
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <hr>

{% endblock %}

templates/listviews/ipaddresses.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}Felis{% endblock %}

{% block content %}
    <table class="table">
            <tr>
                <th>#</th>
                <th>name</th>
                <th>description</th>
                <th>zfs path</th>
                <th>path</th>
                <th>snapshots</th>
            </tr>
        {% for line in object_list %}
            <tr class="clickable-row" data-href="{{ line.get_absolute_url }}">
                <td>{{ line.id }}</td>
                <td>{{ line.name }}</td>
                <td>{{ line.description }}</td>
                <td>{{ line.zpath }}</td>
                <td>{{ line.path }}</td>
                <td>
                    {% if line.snapshots.all %}
                        {% for s in line.snapshots.all %}
                            {{ s.name }}&nbsp;
                        {% endfor %}
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>

    <hr>

{% endblock %}

templates/listviews/jails.html
{% extends 'base.html' %}
{% load bootstrap3 i18n %}
{% block title %}Filesystems{% endblock %}

{% block content %}
    <div class="tabbable">
    <table class="table table-striped table-bordered">
            <tr>
                <th>#</th>
                <th>name</th>
                <th>description</th>
                <th>path</th>
                <th>snapshots</th>
                <th>skel</th>
            </tr>
        {% for line in object_list %}
            <tr class="clickable-row" data-href="{{ line.get_absolute_url }}">
            <th scope="row">
                <td>{{ line.id }}</td>
                <td><a href="{{ line.get_absolute_url }}">{{ line.name }}</a></td>
                <td>{{ line.description }}</td>
                <td>{{ line.zpath }}</td>
                <td>
                    {% if line.snapshots.all %}
                        {% for s in line.snapshots.all %}
                            {{ s.name }}&nbsp;
                        {% endfor %}
                    {% endif %}
                </td>
                <td>{{ line.base.path }}</td>
                <div class="pull-right">
                    {% if model.add_url %}
                        <a href="{{ model.add_url }}" class="btn btn-xs addlink"><span class="glyphicon glyphicon-plus"></span>
                            {% trans 'Add' %}</a>
                    {% endif %}
                    {% if model.admin_url %}
                        <a href="{{ model.admin_url }}" class="btn btn-xs changelink"><span class="glyphicon glyphicon-edit"></span>
                            {% trans 'Change' %}</a>
                    {% endif %}
                </div>
            </tr>
        {% endfor %}
    </table>
    </div>
    <hr>

{#    {% bootstrap_pagination lines size="small" %}#}
{% endblock %}

templates/listviews/transactions.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load tags %}
{% load tz %}
{% block title %}Transactions{% endblock %}

{% block content %}
<div class="panel-group" id="accordion">
    {% for i in object_list %}
        <div class="panel">
            <div class="panel-heading btn btn-xs {% if i.committed %}btn-success{% elif line.rolledback %}btn-danger{% else %}btn-info{% endif %}" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ i.pk }}" style="text-align:left; width: 100%;">
                <div class="panel-title">
                    <div style="display: inline-flex">
                        <b>#{{ i.pk }}</b>
                    </div>
                    <div style="display: inline-flex" class="col-sm-offset-1">
                        for &lt{{ i.instance }}&gt
                        {{ i.get_change_type_display }}
                        {% if i.field %}
                            {% with i.field as f %}{{ i.field }} from {{ i.old_values_dict|get:f}} to {{ i.new_values_dict|get:f }}{% endwith %}
                        {% elif i.fields %}
                            updating {{ i.fields|truncatechars:45 }}
                        {% endif %}
                    </div>
                    <div style="display: inline-flex; float: right">
                        {% if i.author %} by {{ i.author }}{% endif %}&nbsp on {{ i.created|localtime }}
                    </div>
                </div>
            </div>

            <div id="collapse{{ i.pk }}" class="panel-collapse collapse{# {% if forloop.first %}in{% endif %} #}">
                <div class="panel-body">
                    <div><b>value</b> {{ i.value }}</div>
                </div>
                <div class="panel-body">
                    <div class="col-sm-4"><b>old values &nbsp</b><pre style="white-space: pre-wrap">{{ i.old_values_dict|json_prettyfy }}</pre></div>
                    <div class="col-sm-4"><b>new values &nbsp</b><pre style="white-space: pre-wrap">{{ i.new_values_dict|json_prettyfy }}</pre></div>
                    <div class="col-sm-4"><b>cached values &nbsp</b><pre style="white-space: pre-wrap">{{ i.cached_data|json_prettyfy }}</pre></div>
                </div>
            </div>
        </div>
    {% endfor %}
    <hr>
    {% paginator object_list request %}
</div>
{% endblock %}

{% block context_menu %}
    {% if show_system %}
    <a href="{% url 'transactions' %}">Don't show system transactions</a>
    {% else %}
    <a href="{% url 'transactions' %}?show_system=true">Show system transactions</a>
    {% endif %}
    <hr>
{% endblock %}